// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/toko-api/app"
	"github.com/Mpayy/toko-api/controller"
	"github.com/Mpayy/toko-api/middleware"
	"github.com/Mpayy/toko-api/repository"
	"github.com/Mpayy/toko-api/service"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	productRepository := repository.NewProductRepository()
	db := app.NewDb()
	validate := ProvideValidator()
	productService := service.NewProductService(productRepository, db, validate)
	productsController := controller.NewProductsController(productService)
	categoryRepository := repository.NewCategoryRepository()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	router := app.NewRouter(productsController, categoryController)
	authMiddleware := middleware.NewMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)

var productSet = wire.NewSet(repository.NewProductRepository, service.NewProductService, controller.NewProductsController)

func ProvideValidator() *validator.Validate {
	return validator.New()
}
